### ISSUE TITLE
家具の回転の機能を実装する

### ISSUE THREAD

**Issue by no-white-merci** [immobilien2/Immobilien2#6]
家具の向きを自由に回転できる機能の実装
現在は、向きは回転するが、配置すると、Prefabの向きに引っ張られてしまい、元の向きに戻ってしまうバグを修正しているところ。

**Comment by TenshouSu** [comment]
既に実現した。

左右回転機能しかない：https://github.com/immobilien2/Immobilien2/blob/master/KaguRotation_LRonly.cs

上下左右回転できる：
https://github.com/immobilien2/Immobilien2/blob/master/KaguRotation.cs

**Comment by no-white-merci** [comment]
ありがとうさぎ！
